# Generated by Django 3.1.2 on 2020-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analisis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeinforme',
            name='porcentaje_horizontal',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lineadeinforme',
            name='porcentaje_vertical',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
