# Generated by Django 3.1.2 on 2020-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analisis', '0002_auto_20201104_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='conclusion_horizontal',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='conclusion_vertical',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='ratiosanalisis',
            name='conclusion',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
