# Generated by Django 3.1.2 on 2020-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analisis', '0002_auto_20201116_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadeinforme',
            name='porcentaje_horizontal',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='lineadeinforme',
            name='porcentaje_vertical',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='lineadeinforme',
            name='variacion_horizontal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
