# Generated by Django 3.1.2 on 2020-10-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('idRatio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('nomRatio', models.CharField(max_length=50)),
            ],
        ),
    ]
