# Generated by Django 3.1.2 on 2020-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('idGiro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGiro', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=2)),
            ],
        ),
    ]
