<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-06 02:30
=======
# Generated by Django 3.1.2 on 2020-11-03 21:59
>>>>>>> main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Giro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('rasonsocial', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('nrc', models.CharField(max_length=8)),
                ('nit', models.CharField(max_length=17)),
                ('direccion', models.CharField(max_length=100)),
                ('idGiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giro.giro')),
            ],
        ),
    ]
