# Generated by Django 3.1.2 on 2020-11-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estados', '0001_initial'),
        ('Giro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(max_length=13)),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('1', 'Activo Corrinte'), ('2', 'Activo no Corrinte'), ('3', 'Pasivo Corrinte'), ('4', 'Pasivo no Corrinte'), ('5', 'Capital'), ('6', 'Estado de Resultado')], max_length=25)),
                ('naturaleza_cuenta', models.CharField(choices=[('1', 'Acreedor'), ('2', 'Deudor')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('rasonsocial', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('nrc', models.CharField(max_length=8)),
                ('nit', models.CharField(max_length=17)),
                ('direccion', models.CharField(max_length=100)),
                ('BalancesDeEmpresa', models.ManyToManyField(through='Empresa.BalanceEmpresa', to='Estados.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuentaResultado',
            fields=[
                ('idSaldoResul', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo_Resul', models.DateField()),
                ('monto_saldo_Resul', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuentaBalace',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo', models.DateField()),
                ('monto_saldo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta')),
                ('idbalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='EstadosDeEmpresa',
            field=models.ManyToManyField(through='Empresa.EstadoEmpresa', to='Estados.EstadoDeResultado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='idGiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giro.giro'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='balanceempresa',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='balanceempresa',
            name='idbalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance'),
        ),
    ]
