# Generated by Django 3.1.2 on 2020-11-19 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Giro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(max_length=13)),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('Activo Corriente', 'Activo Corriente'), ('Activo no Corriente', 'Activo no Corriente'), ('Pasivo Corriente', 'Pasivo Corriente'), ('Pasivo no Corriente', 'Pasivo no Corriente'), ('Capital', 'Capital'), ('Estado de Resultado', 'Estado de Resultado')], max_length=25, null=True)),
                ('naturaleza_cuenta', models.CharField(choices=[('Acreedor', 'Acreedor'), ('Deudor', 'Deudor')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('rasonsocial', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('nrc', models.CharField(max_length=8)),
                ('nit', models.CharField(max_length=17)),
                ('direccion', models.CharField(max_length=100)),
                ('BalancesDeEmpresa', models.ManyToManyField(through='Empresa.BalanceEmpresa', to='Estados.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='SobreNombre',
            fields=[
                ('idSobreNombre', models.AutoField(primary_key=True, serialize=False)),
                ('sobreNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuentaResultado',
            fields=[
                ('idSaldoResul', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo_Resul', models.DateField()),
                ('monto_saldo_Resul', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuentaBalace',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo', models.DateField()),
                ('monto_saldo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta')),
                ('idbalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='EstadosDeEmpresa',
            field=models.ManyToManyField(through='Empresa.EstadoEmpresa', to='Estados.EstadoDeResultado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gerente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='idGiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giro.giro'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idSobreNombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresa.sobrenombre'),
        ),
        migrations.AddField(
            model_name='balanceempresa',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='balanceempresa',
            name='idbalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance'),
        ),
    ]
