# Generated by Django 3.1.2 on 2020-11-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNombre',
            fields=[
                ('idSobreNombre', models.AutoField(primary_key=True, serialize=False)),
                ('sobreNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='naturaleza_cuenta',
            field=models.CharField(choices=[('Acreedor', 'Acreedor'), ('Deudor', 'Deudor')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Activo Corrinte', 'Activo Corrinte'), ('Activo no Corrinte', 'Activo no Corrinte'), ('Pasivo Corrinte', 'Pasivo Corrinte'), ('Pasivo no Corrinte', 'Pasivo no Corrinte'), ('Capital', 'Capital'), ('Estado de Resultado', 'Estado de Resultado')], max_length=25),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idSobreNombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresa.sobrenombre'),
        ),
    ]
