# Generated by Django 3.1.2 on 2020-11-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estados', '0001_initial'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoDeCuentaBalace',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo', models.DateField()),
                ('monto_saldo', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuentaResultado',
            fields=[
                ('idSaldoResul', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo_Resul', models.DateField()),
                ('monto_saldo_Resul', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='naturaleza_cuenta',
            field=models.CharField(choices=[('1', 'Acreedor'), ('2', 'Deudor')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('1', 'Activo Corrinte'), ('2', 'Activo no Corrinte'), ('3', 'Pasivo Corrinte'), ('4', 'Pasivo no Corrinte'), ('5', 'Capital'), ('6', 'Estado de Resultado')], max_length=25),
        ),
        migrations.DeleteModel(
            name='SaldoDeCuenta',
        ),
        migrations.AddField(
            model_name='saldodecuentaresultado',
            name='idCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta'),
        ),
        migrations.AddField(
            model_name='saldodecuentaresultado',
            name='idResultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado'),
        ),
        migrations.AddField(
            model_name='saldodecuentabalace',
            name='idCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta'),
        ),
        migrations.AddField(
            model_name='saldodecuentabalace',
            name='idbalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance'),
        ),
    ]
