# Generated by Django 3.1.2 on 2020-11-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estados', '0001_initial'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(max_length=13)),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=25)),
                ('naturaleza_cuenta', models.CharField(max_length=12)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDeCuenta',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False)),
                ('year_saldo', models.DateField()),
                ('monto_saldo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.cuenta')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
                ('idbalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
                ('idResultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.estadoderesultado')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
                ('idbalance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estados.balance')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='BalancesDeEmpresa',
            field=models.ManyToManyField(through='Empresa.BalanceEmpresa', to='Estados.Balance'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='EstadosDeEmpresa',
            field=models.ManyToManyField(through='Empresa.EstadoEmpresa', to='Estados.EstadoDeResultado'),
        ),
    ]
