# Generated by Django 3.1.2 on 2020-11-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Giro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('idRatio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('nomRatio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='datogiro',
            name='idRatio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Giro.ratios'),
        ),
    ]
